server:
  port: 7080

#ribbon:
#  eureka:
#   enabled: false

#calculate:
#  ribbon:
#    listOfServers: localhost:7070

#logging:
#  level:
#    org.apache.http: trace

provider:
  url: localhost:7070/test